project:
  type: website
  output-dir: docs
  

website:
  title: "RCN"
  favicon: brasao.png
  navbar:
    logo: brasao.png
    background: primary
    left:
      - href: index.qmd
        text: Início
      - href: professores/professores.qmd
        text: Professores
      - href: ensino/ensino.qmd
        text: Ensino
      - href: pesquisa/pesquisa.qmd
        text: Pesquisa
      - href: extensao/extensao.qmd
        text: Extensão
      - href: laboratorio/laboratorio.qmd
        text: Laboratório
      - text: contato
        href: mailto:rcn.rhs@id.uff.br

format:
  html:
    theme: 
      light: Materia
      dark: darkly
    toc: false
    lang: pt
    date-format: DD/MM/YYYY
    link-external-icon: false
    link-external-newwindow: true

css: styles.css
editor: source